### ISSUE TITLE
`~/.scripts/` not added to `$PATH` for some users

### ISSUE THREAD

**Issue by LukeSmithxyz** [LukeSmithxyz/LARBS#29]
This was voiced by user @ExploXd on LukeSmithxyz/voidrice#64 but I've gotten other emails to the same effect.

After running LARBS, even when the line `export PATH=$PATH:$HOME/.scripts` is in `~/.bash_profile`, some users still cannot run scripts in `~/.scripts/` natively.

Notes:

+ I have never been able to reproduce this error on any of my machines. It's not a universal problem.
+ When users run `echo $PATH`, the scripts directory is not present.
+ Users are indeed using bash, not zsh or something else.

Possible causes:

+ Some other installed program for these people is overwriting `$PATH` as the default value.
+ Some system problem, possible in installation by users, that prevents `$PATH` from being exported properly.

If anyone has any ideas as to what could be causing this, feel free to share.

**Comment by ExploXd** [comment]
could xdg-utils + perl-file-mimeinfo and mimeo cause this? 

here is dummy guide i wrote for one game:

https://pastebin.com/X76u2y4b

**Comment by CecileGS** [comment]
A hackish workaround is to just re-clone Luke's `.bashrc` `.bash_profile` and `.bash_shortcuts` again after every time the aliases/`$PATH` stops working as expected.

**Comment by LukeSmithxyz** [comment]
@ExploXd I don't know. Does your problem end when not using it?

@CecileGS I don't really understand how that would help. The files are still there in the intended format, the exporting just isn't working.

**Comment by ExploXd** [comment]
well it's not causing the issue.

**Comment by ExploXd** [comment]
adding just `~/.bash_profile ` in .bashrc may help.

**Comment by ExploXd** [comment]
`bash: /home/yuri/.bash_profile: Permission denied` This could be also permissions issue.

**Comment by LukeSmithxyz** [comment]
Yes, I think that adding a line like `PATH=$PATH:$HOME/.scripts` to the `bashrc` should fix it (albeit this would have to run every time you open a terminal), but I'd like to figure out what's wrong with the profile. Can you try that out and see if it works?

So you don't have permission to run `.bash_profile`? That's definitely a proximal cause. Can you show me `ls -l ~/.bash_profile`?

**Comment by CecileGS** [comment]
@ExploXd do you mind sharing the contents of your `.bashrc` `.bash_profile` and `progs` if you don't mind and there aren't really any sensitive info in them?

**Comment by luukvbaal** [comment]
I'm experiencing the same issue. Adding `PATH=$PATH:$HOME/.scripts` to `.bashrc` didn't fix it either.
`ls -l ~/.bash_profile` yields 
`-rw-r--r-- 1 luuk wheel 294 Jul  9 12:38 .bash_profile`

**Comment by CecileGS** [comment]
I just made a PR to the `voidrice` repo, I think this may solve this issue in the tracker entirely. However if not, then it is at least a sanity check for troubleshooting some common $PATH problems that may arise for users. My guess is that sometimes for whatever reason, there may be a space character lying somewhere around in either the `$PATH` or `$HOME` variables, which causes the Bash syntax interpreter to be confused and therefore give us an unexpected/unwanted behavior.

PR:
https://github.com/LukeSmithxyz/voidrice/pull/73/commits/239f7a80ddac858c4f015e6450c80f5841d10f6c

Please also see:
https://stackoverflow.com/questions/14637979/how-to-permanently-set-path-on-linux-unix
https://stackoverflow.com/questions/33318499/should-i-use-quotes-in-environment-path-names

**Comment by LukeSmithxyz** [comment]
Okay, so this issue is still alive and well, but thankfully, I made it worse and thus figured out some more.

Thanks to a help email I got today after I made a recent update (that defines i3's terminal in the `profile`), it was revealed that the problem isn't just `$PATH`, but all of `~/.profile`/`~/.bash_profile`. For some people it doesn't get sourced on login at all for some reason.

I'm still baffled as to why, so people with the error are invited to tell any and all modifications they make to their systems, including which packages they choose to install at the outset.

Perhaps there's something I don't know, but it was my understanding that `~/.profile` is always sources on log in, and environmental variables exported by it should thus me persistent, but for some reason, it isn't working for everyone.

**Comment by LukeSmithxyz** [comment]
Okay, I did a little more research and I had had a misunderstanding that might be the source of the problem. I'm going to go out on a limb and say the people who are having this error are using Display managers/login screen.

I had the false idea that `~/.profile` is always sourced in Arch on login, but it ends up that if you use a DM, the file you want is `~/.xprofile`! Crap! Sorry GUI-cucks! I suspect that this is what has been causing all these problems.

I've pushed a change that now links `~/.xprofile` to `~/.profile`, which should solve this problem for good. Tomorrow I'll test it with a DM myself, but if anyone is still having problems, I encourage you to link the files and see if that works. I'll finally close this issue if that's it.

**Comment by LukeSmithxyz** [comment]
Okay. I've "figured it out". The reason I never got this error is because usually when I test LARBS, I do not select to install the optional programs for speed sake and because I didn't think any of them could possibly cause breakage, but it seems that that indeed is the cause of the problem. I just installed an instance with all selected packages and am having this un-sourced `~/.profile` problem.

The thing is, I haven't been able to determine the exact cause, so those of you who have had this problem, could you say which selection(s) you made on script start-up:

- LaTeX packages
- Libreoffice
- GIMP
- Blender
- Emacs
- Fonts for unicode and other languages
- Transmission torrent client
- Music visualizers and decoration
- Pandoc and R/Rmarkdown

If anyone could think of how any of these programs would break `~/.profile`, feel free to divulge,

As I said in #30 I sort of want to get rid of this menu anyway or replace it with a post-install script, so it might not make a difference, but I'm curious what was causing this problem.

**Comment by LukeSmithxyz** [comment]
I believe this has been fixed now and the dotfiles should now work. If you have already installed LARBS and want the fix, run the following as your user:

```
curl https://raw.githubusercontent.com/LukeSmithxyz/voidrice/master/.profile > ~/.profile
rm -f ~/.bash_profile ~/.xprofile
ln -s ~/.profile ~/.bash_profile
ln -s ~/.profile ~/.xprofile
```
Then reboot and log in.

I don't know when this error cropped up, but it's had various causes. Originally, some people used DMs or Arch-based distros with them which caused the `~/.bash_profile` not to load. I then renamed it to `~/.profile` since I thought this would be loaded regardless (as I said above the file I really needed was `~/.xprofile` on Arch distros). A more recent problem was one of the optional programs or something else (which I don't know what it is, but don't really care at this point) was spawning a `~/.bash_profile` if not present which takes precedence over `~/.profile`, which thus caused more recent problems.

Now the `voidrice` repo will use `~/.profile`, and links both `~/.bash_profile` and `~/.xprofile` to it, meaning there are no stops to miss and the files won't be spawned by other programs. This should avoid the problem on all setups.

I've tested this and it works, so I'm going to close the issue. Just because this has been a persistent problem, I'm going to test some more today and if I run into more problems, re-open it, but I think this is it.
