### ISSUE TITLE
Failing install on Arch 32 bit install.

### ISSUE THREAD

**Issue by ofwinterpassed** [LukeSmithxyz/LARBS#73]
Hi Luke! I really appreciate LARBS and am planning to even use it on my work computer which I'm transitioning to Arch in the begining of next year. I used it as a base on my daughters old netbook with a Atom 32bit cpu but had some issues. Yay wouldn't install because of an error (but my sudoers was correct so it is not the same issue as https://github.com/LukeSmithxyz/LARBS/issues/67 instead the install of yay gives an error about "-mod" option can't be understood). I suspect that this is since i686 repos are a bit out of date (firefox wouldn't start either because of a mismatching icu version).

LARBS also failed to install the dotfiles properly and e.g. my .config/i3/config only contained the line to trigger the help and nothing else.

Since this was on an alternative architecture I don't know if it is worth looking into but wanted you to know about it anyway. Maybe it can lead to some improvement.

Thanks for the awesome work you're doing!

**Comment by Kpodov** [comment]
Hey Luke. Thank you for providing this! This is one of the best things ever.
Hey @ofwinterpassed , I just installed larbs in one of my old Thinkpad x60 32 bits. I initially encountered the same issue but this how I fixed it. The problem was with the graphics.

1.After logging out and then back into my user account (where I have larbs installed):
**`pacman -Syu xf86-video-intel`**

2. Then I make this file: 
**`vim /etc/X11/xorg.conf.d/20-intel.conf`**

3. Where I pasted this:

_Section "Device"
  Identifier  "Intel Graphics"
  Driver      "intel"
EndSection_

4. Reboot and then sign back in! 
For more info, you can look here (under "Xorg configuration"):  [https://wiki.archlinux.org/index.php/intel_graphics#Enable_GuC_/_HuC_firmware_loading](url)


Hope this helps! Cheers

**Comment by ofwinterpassed** [comment]
While I had issues that looked like it had to do with graphics installing the drivers and setting xorg configuration didn't solve it. For me installing some of the missing packages from larbs and manually installing the dot files solved my issues. The video driver was already installed.

**Comment by LukeSmithxyz** [comment]
Thanks for bringing this to my attention, but as you say, since the 32bit stuff is out of date, there's not too much I can do. I suspect as time goes on, _even more_ will break.

I could put a lot of ad-hockery in the script to make it instantly compatible with Parabola or Arch 32 or other similar distros, but that sort of opens the door to a borderless to-do list, so I sort of keep this script up to date with just standard Arch.

Now if yay is the main cause of the problem, you might be to just give the script a new AUR manager with `-a`. I don't know though, it might depend on the particulars.

**Comment by ofwinterpassed** [comment]
Considered fixed by possible workaround.
